### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by esamson** [dorkbox/SystemTray#121] opened 2020-05-01 01:07 UTC
Hi,

Would it be possible to publish an updated release? Specifically, the fix for #68 would be very useful for me but that's unfortunately missed the last release by a couple of commits. Is the current master in a publish-worthy state or can we publish just a very minor bump?

Thanks for your work on this very cool library.

**Comment by dorkbox** [comment] 2020-05-05 17:27
Yea, I'll work on a new release. I have to make some changes, and have been busy with work - so it has been on the back-burner a while.

**Comment by ToMe25** [comment] 2020-05-28 13:40
I just started with this library, any news on this?

**Comment by janvonde** [comment] 2021-02-04 08:03
Hey @dorkbox I can see quite some activity in this repo the last days. Can we expect a new release soon? :sunglasses:

**Comment by dorkbox** [comment] 2021-02-04 09:48
That's the plan!

**Comment by janvonde** [comment] 2021-02-04 09:52
Awesome. Thanks for your quick response. Really looking forward to it, thanks for your great work! :smile:

**Comment by hinca** [comment] 2021-04-06 12:47
@dorkbox we are unfortunately also unable to use the framework due to the incompatibilities with modern Java versions.

Is it reasonable to attempt to build a custom 4.0-SNAPSHOT from source, and if so, what is the recommended approach? Thanks!

**Comment by dorkbox** [comment] 2021-04-06 13:05
4.0 will be releasing shortly, at the end of today or by tomorrow.

It was planned last week, but there were some regression tests that failed on Arch.

**Comment by maztan** [comment] 2021-04-06 13:09
Great! Can't wait :)

**Comment by dorkbox** [comment] 2021-04-07 15:10
Release is soon, so I'm closing this support issue.

**Closed by dorkbox** 2021-04-07 15:10 UTC
