### ISSUE TITLE
Not supported to KDE (Kali Linux)?

### ISSUE THREAD

**Issue by ardikars** [dorkbox/SystemTray#55] opened 2017-05-24 06:25 UTC
13:20:44.695 [main] ERROR dorkbox.systemTray.SystemTray - Attempting to load the SystemTray as the 'root' user. This will likely not work because of dbus restrictions.
13:20:45.343 [main] WARN dorkbox.systemTray.SystemTray - Unable to initialize the AppIndicator correctly, falling back to GtkStatusIcon type
13:20:45.782 [main] INFO dorkbox.systemTray.SystemTray - Successfully loaded

**Comment by dorkbox** [comment] 2017-06-14 22:43
The issue is that you are logged in as root, and as you can see -- AppIndicator tries to load, and if GtkStatusIcon (the fallback) works fine -- can you post more specific OS info (ie: which version of Kali, and which version of java?) so I can add a manual entry and remove the warning?

The problem is that if it's an elevated root user, it dbus cannot communicate to the logged in user. I'll look into this more, as I know that the default login for Kali is root, and if the only logged in user is root, it might not be an issue at all.


Thanks for opening the issue to bring this to my attention.

**Comment by dorkbox** [comment] 2017-07-22 16:20
fixed in 03b7cdbcb775b2d4cf2f519d7d9191a74cbae16f

**Closed by dorkbox** 2017-07-22 16:20 UTC
