### ISSUE TITLE
Open Source status of SystemTray dependencies

### ISSUE THREAD

**Issue by pietrygamat** [dorkbox/SystemTray#138] opened 2021-02-12 01:02 UTC
Currently the source from the master branch cannot be built as the required dependencies are not published to maven central. From what I can tell their sources are not in this repository and are also not available anywhere publicly. Would you care to throw the code into some repository "as is", so we can at least try to evaluate the 4.0 goodies? I understand publishing to maven requires some level of polish, but it's not the case with git, I believe. 
Or perhaps I simply cannot find it, in which case, I'd appreciate being pointed the right way.

**Comment by dorkbox** [comment] 2021-02-12 10:21
I'll release it -- it's not found because I haven't released it yet.

There a quite a few structural changes in these dependencies, along with working out multi-release jars/different java releases, and so I have been locally testing. Once I have done a basic sanity test for linux and macos (windows is finished) ... I'll release them to maven. It should be this weekend.

**Comment by dorkbox** [comment] 2021-03-22 09:59
update:  Sorry it wasn't sooner, but I've been busy. Work is being done on JPMS support right now, then a last round of regression, and then release.

**Comment by dorkbox** [comment] 2021-04-07 15:11
Release is soon, so I'm closing this support issue.

**Closed by dorkbox** 2021-04-07 15:11 UTC

**Comment by tchabaud** [comment] 2021-11-10 11:01
Hello @dorkbox sorry to bump this old issue, but did the release happened ? I can't found the libraries on maven central.

**Comment by dorkbox** [comment] 2021-11-10 12:09
No apology needed. 

:( sadly no, the JPMS support that was planned did not work out as expected. Because there was a lot going on with work, I wasn't able to finish the release. Fortunately, what is remaining can be finished over the Christmas holidays.

JPMS is quite horrid when there are requirements on other libraries that do not support JPMS in a multi-platform environment.

**Comment by t-chab** [comment] 2021-11-15 16:39
Ok, thanks for the details :+1: 

Good luck for the JPMS migration !
