### ISSUE TITLE
OpenJDK+OpenJFX 11 GTK versions issue

### ISSUE THREAD

**Issue by Tristan971** [dorkbox/SystemTray#95] opened 2018-11-12 21:12 UTC
Hello, using OpenJDK 11 (and the module-path, unsure if that even matters here),

I get the same issue as in #17 even with `SystemTray.FORCE_GTK2 = true;`.

That happens with your `TestTrayJavaFX` test class (in `SystemTray` repo).

Full output is :
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by dorkbox.util.Swt (file:/home/tristan/.m2/repository/com/dorkbox/SystemTray/3.17/SystemTray-3.17.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of dorkbox.util.Swt
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21:04:56.249 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - OS: Linux
21:04:56.253 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Arch: amd64
21:04:56.254 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 11.0.1
21:04:56.254 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is Auto sizing tray/menu? true
21:04:56.254 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is JavaFX detected? true
21:04:56.254 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is SWT detected? false
21:04:56.409 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Java Swing L&F: Metal
21:04:56.409 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Auto-detecting tray type
21:04:56.409 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Force GTK2: true
21:04:56.409 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Prefer GTK3: true
21:04:56.459 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Currently using the 'Unknown' desktop environment
Manjaro Linux
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
Manjaro Linux
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.0
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"

21:04:56.514 [JavaFX Application Thread] DEBUG dorkbox.util.jna.linux.GtkLoader - GTK: gtk-x11-2.0
21:04:56.515 [GTK Native Event Loop] DEBUG dorkbox.util.jna.linux.GtkEventDispatch - Running GTK Native Event Loop

(java:19065): Gtk-ERROR **: 21:04:56.515: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

Process finished with exit code 133 (interrupted by signal 5: SIGTRAP)
```

You can run your test case locally with openjdk11+openjfx11 using branch `ojdk11-systray` of https://github.com/Tristan971/Lyrebird and using JDK from https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot

Hope we can get this fixed as I deprecated all my personal work on system tray in favor of yours :d

**Comment by dorkbox** [comment] 2018-11-28 13:51
That's an issue with using reflection (for both SWT and JavaFX) - it will be resolved in the next release.

**Comment by tomasfrtala** [comment] 2019-01-14 12:08
@dorkbox can you please estimate when it will be fixed?

**Comment by dorkbox** [comment] 2019-01-14 13:32
Sorry it's taken so long - I've been swamped with work. I estimate the fix will be this week.

**Comment by polyn0m** [comment] 2019-03-22 20:21
@dorkbox any news?

**Comment by dorkbox** [comment] 2019-03-22 20:40
There was a build-system issue (which was recently fixed). I plan to get this + some other bugs fixed this weekend.

**Comment by p-** [comment] 2019-05-02 05:19
Has anybody found a working workaround for this issue (besides downgrading Java)?

**Comment by Tristan971** [comment] 2019-05-02 09:38
Not yet AFAIK. Our friend dorkbox seems quite busy lately, and I kind of want this lib to grow so I'll try and find some time to contribute on the native side too.

**Comment by dorkbox** [comment] 2019-05-13 16:04
I got a new build incoming (last thing to do is fix the SWT/JavaFX reflection access errors), then I'll be able to look into this.

**Comment by dorkbox** [comment] 2019-06-09 15:16
I am waiting on a response to this issue: https://github.com/java-native-access/jna/issues/1099

**Comment by alexxxdev** [comment] 2020-05-06 03:21
Hi, are there any changes on this issue?

**Comment by fsufitch** [comment] 2020-09-16 00:15
Bump. Still running into this problem.

**Comment by dorkbox** [comment] 2020-10-08 23:26
Just a heads up, I've started working on this project again.

**Comment by NangiDev** [comment] 2020-10-10 16:12
I found this thread on forcing javafx/tornadofx into GTK 3

https://stackoverflow.com/a/22457177/3021593

**Comment by NangiDev** [comment] 2020-10-10 19:25
I managed to get it working as I needed it to by doing this
https://gist.github.com/NangiDev/9b8adfec2e9684dc93353622f603fee3

**Comment by dorkbox** [comment] 2020-11-01 13:15
The problem is that closing the javaFX window shuts down the javafx event dispatch - which is why the tray freezes.

I'm not sure the best way to solve this issue :/

**Comment by NangiDev** [comment] 2020-11-06 09:17
My idea was to override the shutdown event and just having the close button hiding the window, but that did not seem to work either.

**Comment by maztan** [comment] 2021-03-24 15:04
This issue prevents usage of this library on JDK 12 on Ubuntu (18 in my case)

**Comment by dorkbox** [comment] 2021-03-28 22:03
Fixed.

If `installShutdownHook()` is called for tray (it's no longer a static variable), then when JavaFX/SWT/etc is closed, then the tray is **also** closed.

If this is **not** called, then when you close the JavaFX/SWT window, the SystemTray will continue to run.


Thanks for the initial bug report, this is a good feature to have, and required a bit of architectural changes to get working!

**Closed by dorkbox** 2021-03-28 22:03 UTC
